services:
  postgres:
    extends:
      file: infra/docker-compose.yml
      service: postgres

  redis:
    extends:
      file: infra/docker-compose.yml
      service: redis

  backend:
    extends:
      file: infra/docker-compose.yml
      service: backend

  frontend:
    extends:
      file: infra/docker-compose.yml
      service: frontend

volumes:
  pgdata:
