from __future__ import annotations

import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.evidence.models import Evidence, EvidenceDedupLog, Jurisdiction, SourceType
from app.modules.ingestion.connectors.base import IngestionItem
from app.modules.ingestion.service import DeduplicationService, DocumentProcessor, IngestionService


@pytest.fixture
def mock_db():
    db = AsyncMock(spec=AsyncSession)
    return db


@pytest.fixture
def sample_item():
    item = IngestionItem(
        source_id=uuid.UUID("00000000-0000-0000-0000-000000000001"),
        source_name="RBI",
        original_url="http://rbi.org.in/1",
        publisher="rbi.org.in",
        title="RBI Monetary Policy",
        raw_content="RBI keeps repo rate unchanged at 6.5%",
        publication_ts=datetime.now(timezone.utc),
        jurisdiction=Jurisdiction.IN,
        source_type=SourceType.RSS,
        metadata={"category": "monetary_policy"},
    )
    # evidence_id is generated by connector's _build_ingestion_item
    item.evidence_id = "test-evidence-id"
    return item


@pytest.mark.asyncio
async def test_deduplication_exact_duplicate(mock_db, sample_item):
    dedup = DeduplicationService(mock_db)

    existing = Evidence(
        id=uuid.uuid4(),
        evidence_id="existing-id",
        source_id=sample_item.source_id,
        source_name="RBI",
        content_hash=sample_item.content_hash,
        near_dup_hash=sample_item.near_dup_hash,
    )

    mock_result = MagicMock()
    mock_result.scalar_one_or_none.return_value = existing
    mock_db.execute.return_value = mock_result

    result = await dedup.check_exact_duplicate(sample_item.content_hash)
    assert result is existing


@pytest.mark.asyncio
async def test_deduplication_no_duplicate(mock_db, sample_item):
    dedup = DeduplicationService(mock_db)

    mock_result = MagicMock()
    mock_result.scalar_one_or_none.return_value = None
    mock_db.execute.return_value = mock_result

    result = await dedup.check_exact_duplicate(sample_item.content_hash)
    assert result is None


@pytest.mark.asyncio
async def test_deduplication_near_duplicate(mock_db, sample_item):
    dedup = DeduplicationService(mock_db)

    existing = Evidence(
        id=uuid.uuid4(),
        evidence_id="near-dup-id",
        source_id=sample_item.source_id,
        source_name="RBI",
        content_hash="different_hash",
        near_dup_hash=sample_item.near_dup_hash,
    )

    mock_result = MagicMock()
    mock_result.scalars.return_value.all.return_value = [existing]
    mock_db.execute.return_value = mock_result

    result = await dedup.check_near_duplicate(sample_item.near_dup_hash)
    assert result is existing


@pytest.mark.asyncio
async def test_log_deduplication(mock_db):
    dedup = DeduplicationService(mock_db)

    await dedup.log_deduplication(
        uuid.uuid4(),
        uuid.uuid4(),
        "exact",
        1.0
    )

    mock_db.add.assert_called_once()
    added_log = mock_db.add.call_args[0][0]
    assert isinstance(added_log, EvidenceDedupLog)
    assert added_log.dedup_type == "exact"
    assert added_log.similarity_score == 1.0


@pytest.mark.asyncio
async def test_ingestion_service_process_item_exact_dup(mock_db, sample_item):
    mock_db.execute = AsyncMock()
    mock_db.execute.return_value.scalar_one_or_none.return_value = None
    mock_db.execute.return_value.scalars.return_value.all.return_value = []

    mock_db.flush = AsyncMock()

    service = IngestionService(mock_db)

    # First call - should insert
    await service._process_item(sample_item, uuid.uuid4())
    assert mock_db.add.called

    # Second call with same content hash - should log dedup
    existing_evidence = MagicMock(id=uuid.uuid4())
    mock_db.execute.return_value.scalar_one_or_none.return_value = existing_evidence
    await service._process_item(sample_item, uuid.uuid4())


@pytest.mark.asyncio
async def test_document_processor_initialization():
    processor = DocumentProcessor()
    assert hasattr(processor, '_docling_available')
    assert hasattr(processor, '_paddleocr_available')


@pytest.mark.asyncio
async def test_document_processor_text():
    processor = DocumentProcessor()
    result = await processor._process_text(b"Hello World", "test.txt")
    assert result["text"] == "Hello World"
    assert result["method"] == "text"


@pytest.mark.asyncio
async def test_ingestion_service_run_ingestion(mock_db):
    service = IngestionService(mock_db)

    mock_connector = AsyncMock()
    mock_item = MagicMock(
        evidence_id="test-id",
        source_id=uuid.uuid4(),
        source_name="Test",
        original_url=None,
        publisher="Test",
        title="Test",
        raw_content="Content",
        content_hash="abc123",
        near_dup_hash="def456",
        publication_ts=datetime.now(timezone.utc),
        jurisdiction=Jurisdiction.IN,
        source_type=SourceType.RSS,
        is_mock=False,
        metadata={},
    )
    mock_connector.fetch.return_value = MagicMock(
        items=[mock_item],
        errors=[],
        success_count=1,
        error_count=0,
    )

    service.connectors = {"test": mock_connector}

    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()
    mock_db.execute = AsyncMock()
    mock_db.execute.return_value.scalar_one_or_none.return_value = None
    mock_db.execute.return_value.scalars.return_value.all.return_value = []

    run = await service.run_ingestion(uuid.uuid4(), "test")
    assert run.status in ("completed", "partial")
    assert run.items_ingested >= 0


@pytest.mark.asyncio
async def test_vector_similarity_search():
    pass